version: "3"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  mysql:
    image: mysql:5.6
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  redis:
  mysql:

networks:
  rabbitmq_go_net:
    driver: bridge