version: "3"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  mysql:
    image: mysql:5.6
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  redis:
  mysql: