server.port: 8081
spring:
  redis:
    port: 6379
    host: localhost
    timeout: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open-music-api
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  messages.basename: i18n/messages
